---
- name: Converge
  hosts: all
  remote_user: root
  become: true
  gather_facts: yes
  roles:
    - role: buluma.bootstrap
    - role: buluma.setuptools
    - role: buluma.timezone
    - role: ansible-role-gitlab_ee
